{% set version = '1.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-readxl
  version: {{ version|replace("-", "_") }}

source:
  fn: readxl_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/readxl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/readxl/readxl_{{ version }}.tar.gz
  sha256: 29c8830d42ea7bf3f8671adafb62f2c6e6296f187dc3aa39838ad0a9131a95d7

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.18
    - r-cellranger
    - r-progress
    - r-tibble >=1.3.1
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.18
    - r-cellranger
    - r-progress    
    - r-tibble >=1.3.1

test:
  commands:
    - $R -e "library('readxl')"           # [not win]
    - "\"%R%\" -e \"library('readxl')\""  # [win]

about:
  home: http://readxl.tidyverse.org, https://github.com/tidyverse/readxl
  license: GPL-3
  summary: Import excel files into R. Supports '.xls' via the embedded 'libxls' C library <https://github.com/evanmiller/libxls>
    and '.xlsx' via the embedded 'RapidXML' C++ library <https://rapidxml.sourceforge.net>.
    Works on Windows, Mac and Linux without external dependencies.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
