{% set version = "1.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-readxl
  version: {{ version|replace("-", "_") }}

source:
  fn: readxl_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/readxl_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/readxl/readxl_{{ version }}.tar.gz
  sha256: b63d21fc6510acb373e96deaec45e966a523ec75cbec75a089529297ed443116

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp
    - r-cellranger
    - r-tibble >=1.1

  run:
    - r-base
    - r-rcpp
    - r-cellranger
    - r-tibble >=1.1

test:
  commands:
    - $R -e "library('readxl')"  # [not win]
    - "\"%R%\" -e \"library('readxl')\""  # [win]

about:
  home: http://readxl.tidyverse.org, https://github.com/tidyverse/readxl
  license: GPL-3
  summary: Import excel files into R. Supports '.xls' via the embedded 'libxls' C library <https://sourceforge.net/projects/libxls/>
    and '.xlsx' via the embedded 'RapidXML' C++ library <https://rapidxml.sourceforge.net>.
    Works on Windows, Mac and Linux without external dependencies.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
