appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: a21f7mhDZrqjEVMObTH909q8tRytbaqmftdCzGGY5C/hqIAviAXYtmK39vf/5IDlFoiLXgnMEsvVWHlnGK4nf/tdBLvZaaVZ0vEoOIz8HGYbfIZpp60rjqR3fAm/V0V6z6g3/ORqc0Z18y4zg/sE3wBH6FKLPsSv/JP9dINp+gJvk6U6UEkH2meNVqUw2QBGG/bxya9j9ESc2uejS6jmC4+sfeR6SEA3VAmKlenC3NNhc+ZMXU25fYpbLCYcxw3/xEvkW1Ug6y1hV4/0PHjjjJLf5YFiLCKfk+ptC+56vn5dF2EvwX9ITeLV/oPXvVdTy5zVkC5WikwFLpittvl4o6uPiVpLUMZ/cf29fySdWPiq/GrjjANnCBtaKZqAZUQP5XWWjDGdrUnXf+WiqHlde0PpBYq9gpKglE4tXF8kJ3yTjCTrRkWOi3k2YR6QTqT8PKPLzpAAWZ6t8K3jI3nYbD8i5ojhYcJS5rC3Mny8ubp/T8CCLe04IQGlK6EBad421juNlj3/4KiMqa3yOy/N2CBboLXH3t7+yTSkWOX2eimxINgKYsHISaMhOT1sxnQNjWRvQKidZLzujpcWgv9G3GCG7KTKKn3iSk/kLSSIeMbevFVkeTXXlgrpJxSaB76I2Unkkvm5WoJt+oPfphyfhLkXw3fZfP/G8JaJgOIZLeM=}
